disabled_rules:
  - type_name
  - nesting
  - todo
excluded:
  - .swiftpm
  - .github
  - SourcePackages
  - Build
identifier_name:
  excluded:
    - id
    - v1_0
    - fr
    - en
  allowed_symbols: "_"
trailing_whitespace:
  severity: error
comment_spacing:
  severity: error
line_length:
  error: 120
  ignores_urls: true
file_length:
    warning: 500
    error: 800
    ignore_comment_only_lines: true
function_parameter_count:
    warning: 6
    error: 8
